### PR TITLE
Add more broadcastable primitives 

### PR DESCRIPTION
**Pull request by amellnik**

### CODE REVIEW

**Comment by amellnik** [comment]
This allows leakyrelu to work in a single-layer net, but not inside of `Chain` for some reason that I haven't been able to figure out.

**Comment by jekbradbury** [comment]
This works for me on your branch?

```julia
julia> @code_js Chain(Dense(10, 5, leakyrelu), Dense(5, 1))(rand(10))
let model = (function () {
  let math = dl.ENV.math;
  function hornet(tiger) {
    return math.add(math.matrixTimesVector(model.weights[0], tiger), model.weights[1]);
  };
  function turkey(toad) {
    return math.relu(math.add(math.matrixTimesVector(model.weights[2], toad), model.weights[3]), 0.01);
  };
  function model(aardvark) {
    return hornet(turkey(aardvark));
  };
  model.weights = [];
  return model;
})();
flux.fetchWeights("model.bson").then((function (ws) {
  return model.weights = ws;
}));
```

This also works:
```julia
@code_js Chain(Dense(10, 5, leakyrelu), Dense(5, 5), x -> leakyrelu.(x))(rand(10))
```

**Comment by amellnik** [comment]
@jekbradbury -- You are correct.  I was trying to do 

```julia
@code_js Chain(Dense(32, 128, leakyrelu), Dense(128, 784))(zeros(Float32, 32))
```

instead of 

```julia
@code_js Chain(Dense(32, 128, leakyrelu), Dense(128, 784))(rand(32))
```

which works.  I don't know why it makes a difference, but it's not related to these changes.

**Comment by jekbradbury** [comment]
Well, `rand` would give `Float64`, which I think is Flux's default for
parameters.

**Comment by amellnik** [comment]
Closing in favor of #15.

**Pull request closed without merging**
